### ISSUE TITLE
perform_analyses argument 'name' can be a vector?

### ISSUE THREAD

**Issue by Ly-Cilph** [poissonconsulting/poiscon#5]
Is defined as "a character scalar of the name of the data", but have seen instances of a vector being passed. Presume in this case, perform_analysis loops over separate instances of the data?

**Comment by joethorley** [comment]
Updated documentation:

#' Performs batch jags analyses. It goes through the folders defined by \code{...}
#' and pulls out the data of name \{name} (by default \code{"data"} and then fits
#' the models defined in \code{models}. Note \code{beep = TRUE} has caused
#' crashed with RStudio on windows.
#' 
#' @param models A jags_model object.
#' @param ... A series of character vectors or a list of character vectors of 
#' folders to cycle through.
#' @param niters A count of the number of iterations to perform.
#' @param mode A string of the opts_jagr mode.
#' @param name A string of the name of the data file.
#' @param beep A flag indicating whether to beep on completion.
